server.port=8085

# Toggle between 'mysql' and 'postgres' here
spring.profiles.active=mysql

# Common JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jackson.serialization.fail-on-empty-beans=false